# Generated by Django 6.0.5 on 2026-06-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.SmallIntegerField()),
                ('acao', models.CharField(max_length=60)),
                ('descricao_mudanca', models.TextField(blank=True)),
                ('status_anterior', models.CharField(blank=True, max_length=30)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historico_versoes',
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('resumo_300', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_AVALIACAO', 'Em Avaliação'), ('AVALIADO', 'Avaliado'), ('ARQUIVADO', 'Arquivado')], default='PENDENTE', max_length=20)),
                ('area_tematica', models.CharField(max_length=100)),
                ('link_demo', models.TextField(blank=True, null=True)),
                ('link_repositorio', models.TextField(blank=True, null=True)),
                ('avaliacao_iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projetos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('ZIP', 'ZIP'), ('LINK_EXTERNO', 'Link Externo'), ('IMAGEM', 'Imagem')], max_length=20)),
                ('url', models.TextField()),
                ('versao', models.SmallIntegerField(default=1)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projeto_arquivos',
            },
        ),
        migrations.CreateModel(
            name='ProjetoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel_no_grupo', models.CharField(blank=True, max_length=60)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projeto_membros',
            },
        ),
        migrations.CreateModel(
            name='ProjetoTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologia', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'projeto_tecnologias',
            },
        ),
    ]
