# Generated by Django 6.0.5 on 2026-06-02 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoversao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projeto',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projetos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projeto',
            name='em_avaliacao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_em_avaliacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projeto',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projetos', to='usuarios.turma'),
        ),
        migrations.AddField(
            model_name='historicoversao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='projetoarquivo',
            name='enviado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projetoarquivo',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='projetomembro',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='projetomembro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='projetos_participando', through='projetos.ProjetoMembro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projetotecnologia',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnologias', to='projetos.projeto'),
        ),
        migrations.AlterUniqueTogether(
            name='projetomembro',
            unique_together={('projeto', 'usuario')},
        ),
    ]
