# Generated by Django 6.0.5 on 2026-06-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='publicado_no_feed',
            field=models.BooleanField(default=False),
        ),
    ]
