# Generated by Django 6.0.5 on 2026-06-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
