# Generated by Django 6.0.5 on 2026-06-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_seed_turmas_semestres_3_a_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='hard_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobre_mim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='soft_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
