# Generated by Django 6.0.5 on 2026-06-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceito', models.CharField(choices=[('INSUFICIENTE', 'Insuficiente'), ('AINDA_NAO_SUFICIENTE', 'Ainda não suficiente'), ('BOM', 'Bom'), ('OTIMO', 'Ótimo'), ('EXCELENTE', 'Excelente')], max_length=30)),
                ('feedback_geral', models.TextField(blank=True)),
                ('avaliado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'avaliacoes',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceito', models.CharField(choices=[('INSUFICIENTE', 'Insuficiente'), ('AINDA_NAO_SUFICIENTE', 'Ainda não suficiente'), ('BOM', 'Bom'), ('OTIMO', 'Ótimo'), ('EXCELENTE', 'Excelente')], max_length=30)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'avaliacao_criterios',
            },
        ),
        migrations.CreateModel(
            name='CriterioRubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.SmallIntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'criterios_rubrica',
                'ordering': ['ordem'],
            },
        ),
    ]
