# Generated by Django 6.0.5 on 2026-06-02 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='projeto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='avaliacaocriterio',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='avaliacoes.avaliacao'),
        ),
        migrations.AddField(
            model_name='avaliacaocriterio',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='avaliacoes.criteriorubrica'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaocriterio',
            unique_together={('avaliacao', 'criterio')},
        ),
    ]
