# Generated by Django 6.0.5 on 2026-06-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='rubrica_assinatura',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
