# Generated by Django 6.0.5 on 2026-06-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'canais_chat',
            },
        ),
        migrations.CreateModel(
            name='CanalParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_escrever', models.BooleanField(default=True)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'canal_participantes',
            },
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curtido_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'curtidas',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('ARQUIVO', 'Arquivo'), ('SISTEMA', 'Sistema')], default='TEXTO', max_length=20)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mensagens',
                'ordering': ['enviada_em'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificacoes',
                'ordering': ['-criada_em'],
            },
        ),
    ]
