# Generated by Django 6.0.5 on 2026-06-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalchat',
            name='projeto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canal', to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='canalparticipante',
            name='canal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.canalchat'),
        ),
    ]
