# Generated by Django 6.0.5 on 2026-06-02 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_initial'),
        ('projetos', '0004_grupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canal', to='projetos.grupo')),
            ],
            options={
                'db_table': 'canais_grupo',
            },
        ),
        migrations.CreateModel(
            name='MensagemGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='feed.canalgrupo')),
            ],
            options={
                'db_table': 'mensagens_grupo',
                'ordering': ['enviada_em'],
            },
        ),
    ]
