# Generated by Django 6.0.5 on 2026-06-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_canalgrupo_mensagemgrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemgrupo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='chat_arquivos/'),
        ),
        migrations.AddField(
            model_name='mensagemgrupo',
            name='nome_arquivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mensagemgrupo',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('ARQUIVO', 'Arquivo')], default='TEXTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='mensagemgrupo',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
    ]
